site_name: ChatNomina Documentation
site_description: Documentación del Sistema de Chat Inteligente para Consultas de Nómina
site_author: Universidad Icesi
repo_url: https://github.com/arlexpin/ChatNomina
repo_name: ChatNomina

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Guía de Usuario:
    - Introducción: user_guide/user_guide.md
    - Interfaz: user_guide/interface.md
    - Consultas: user_guide/queries.md
  - Documentación Técnica:
    - Arquitectura: technical/architecture.md
    - Desarrollo: technical/development.md
    - Modelos: technical/models.md
    - Seguridad: technical/security.md
    - Despliegue: technical/deployment.md
  - API:
    - Referencia: api.md
  - Contribución:
    - Guía: contributing.md
  - Anexos:
    - Arquitectura: anexo_a_arquitectura.md
    - Implementación: anexo_b_implementacion.md
    - Evaluación: anexo_c_evaluacion.md
    - Seguridad: anexo_d_seguridad.md
    - Mantenimiento: anexo_e_mantenimiento.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arlexpin/ChatNomina
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/chatnomina/
    - icon: fontawesome/solid/globe
      link: https://www.icesi.edu.co

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 